travis:
  secure:
    BINSTAR_TOKEN: rMckcdx0dh6eU7roweiU2hRWW3PeBFOZi9hqgeBUPZLvZSxR6AxxcedcvzZzb/AAtyZRTwZLrtbgcRZ25S9U2/ieC4dDrhGZdG6e3Ugn6rk+6NaEnmRVROR1Cz6X1SRkEvO1iWOTVA+ndm/81TRYdMsUfDIn5qBrsegfMytPbj12CCbzoUPnKZuMPNMIIMKbhBLYG9BPW5v3eb79FczSzPBQPwfqMBlfGE6JKT+RRUzqIPxJoO7HDbA+TxPl8CTYjhBjxjUdte6ZQxoRg+nTQT0MmE0/hMwBGBa4X6etOpKqi0qLJC88GTy+4tX/MOwtpbYUDeKsWybErETJZrc1hCOmkuB/Mbfy6ROsLZ17a8n6SJYRRHYJw2VYilg3ogJVlZNiQa+GhGUerIifs9gXB6N+NBslzvgmgl7hCn8F7FULTotCZNReatNq8+iy3aqRPPVji3HxKPqENJCjSn3fEiJvio1vRniGc3iYu8+Re5FN2KXnsfS2yinFGCVJsVTAQc5dzFQuFftyLUrgEuZVELB3TrInR6+NyMzkdc3ZuKAjSPwsc8CEfkIMgvWQvTmMEktfbnWPZDYChUVshQJCjS7H3I5gvY3n7nA9+sdAcMCx8+yszA820nVIO0Q3nWoA6LHFZqBbTu8WfSrek4I4pT+F5+gbbKscstXCXJ2os2M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
