appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NnIS/gAH9BdhDTBrZphs84lwJgtVFDudbnxRQRW6xS9Q7CpobwLk9hMCR+JCq+w6/dJhdq+BILPJ9eV6evB1Os7D/NxV4SfGxmIRY4dO5ibzg1aA3AxHSkbjlcnh9in1G+HgVg4CunQFj3d4Bw1KhadgnTFgomQ8evm/BC0ZmryIqy9BRGO/mmF8x8VaF4J2UFz31r1cTsQQDUNcGcqQSk6fwDRNNF1uZUZjQwOD2LaRK67rWSpGGvTQOB7qFbVlmXwN07xDXLNQVfoWHI3UzjPnkn+gI0bxGmtVRup6W5KiHZvEk0Vrtm9AsqkloBKcQrH2ed9b+dsBz6b17QVBOA7sOIk7zU1oEX+5mF1HPdjU0lcE+FtycgcAFUL+VtTcEDQiiOVBs1L/KricCDK7ln8Prpll1IHtT1sQc3JWQEk8xzuHThOoJDOl+5wgDejKd49P3NiTkZWORO0c+9ApjlZzsm6HGU9Jl7l6UxM0TefG2pxxJ5gtFAhfAbqz/3n/c8JoACEjFWYF7/WBesrDe7peN64zFfnBANb0qQAjUV7rso+oO4PvZ7B/SKjTxIQ+k6Miw9xfjRJwrZDiK5Plj8rOMclXaY5HUtz5JlwhSE/82qf0ACpu9+cL8h5/1KMvmKH/1d5BSbI4CZTHk6RyJM4tj8UfiW6xzbx743c6myk=
conda_forge_output_validation: true
